"""Catalog health report: what Samsung's deeplink catalog cannot do, and why.

    python -m tools.catalog_health                          # offline stub for part 2
    python -m tools.catalog_health --provider gemini --rate-limit-rpm 12

Writes docs/catalog_health.md and evaluation/catalog_health.json. Every figure is
computed here; nothing in the markdown is typed by hand.

Part 1 reads data/deeplinks.json alone: labels shared by many screens, entries identical
on every text field, labels their own description does not support, one-sided toggles,
missing link types and validation deeplinks. None of these can be fixed by a better
resolver. They are fixes to the catalog, and the catalog is Samsung's.

Part 2 runs the 20 supplied rows through the real pipeline and lists every Settings step
that got no confident catalog entry, with the resolver's reason. Physical steps and
`manual` actions are excluded: those are correctly unlinked by the specification, not
gaps. What remains is where Samsung's own articles send a customer to a screen the
catalog cannot open with confidence.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.contracts import TroubleshootRequest  # noqa: E402
from app.llm import get_provider  # noqa: E402
from app.llm.replay import ReplayProvider  # noqa: E402
from app.main import run_pipeline  # noqa: E402
from app.pipeline.catalog_audit import audit  # noqa: E402
from app.pipeline.deeplinks import get_catalog  # noqa: E402

MD_PATH = ROOT / "docs" / "catalog_health.md"
JSON_PATH = ROOT / "evaluation" / "catalog_health.json"

# Reasons that mean "correctly unlinked by the specification", not "catalog gap".
BY_DESIGN = {"manual_category_forbids_deeplink", "physical_interaction_not_a_settings_screen"}


def unresolved_steps(provider_name: str, rate_limit_rpm: int = 0) -> Dict[str, Any]:
    rows = json.loads((ROOT / "data" / "siis_responses.json").read_text(encoding="utf-8"))["responses"]
    provider = (ReplayProvider(ROOT / "backend" / "tests" / "fixtures" / "extraction_row21.json")
                if provider_name == "replay" else get_provider(provider_name))
    interval = 60.0 / rate_limit_rpm if rate_limit_rpm > 0 else 0.0
    gaps: List[Dict[str, Any]] = []
    decisions: Counter = Counter()
    next_slot = 0.0
    for row in rows:
        if interval:
            wait = next_slot - time.monotonic()
            if wait > 0:
                time.sleep(wait)
            next_slot = time.monotonic() + interval
        debug: Dict[str, Any] = {}
        run_pipeline(TroubleshootRequest(query=row["original_query"],
                                         siis_response=row["siis_response"]),
                     provider=provider, debug_sink=debug, use_cache=False)
        for r in debug.get("resolutions") or []:
            decisions[(r["decision"], r["reason"])] += 1
            if r["decision"] == "exact" or r["reason"] in BY_DESIGN:
                continue
            gaps.append({
                "row": row["id"],
                "article": (row["siis_response"] or {}).get("title"),
                "action": r["action"],
                "decision": r["decision"],
                "reason": r["reason"],
                "nearest": [{"id": t["catalog_id"], "message": t["message"],
                             "verdict": t["verdict"]} for t in (r.get("rejected") or [])[:3]],
            })
    return {
        "provider": f"{provider.name}:{provider.model}",
        "decisions": [{"decision": d, "reason": why, "n": n}
                      for (d, why), n in decisions.most_common()],
        "gaps": gaps,
    }


def render(a: Dict[str, Any], u: Dict[str, Any], generated: str) -> str:
    lines: List[str] = []
    add = lines.append
    add("# Catalog health")
    add("")
    add(f"Generated by `python -m tools.catalog_health` at {generated}. Part 1 reads "
        "`data/deeplinks.json` alone; part 2 was produced with extraction provider "
        f"`{u['provider']}`. Nothing here is typed by hand.")
    add("")
    add("This is feedback on the catalog, not on the resolver. Every item below limits "
        "ANY system that maps troubleshooting steps to these deeplinks.")
    add("")

    add("## 1. The catalog on its own")
    add("")
    add(f"{a['n_entries']} real entries (the `dummy_positive` placeholder excluded), "
        f"{a['n_unique_uris']} unique URIs.")
    add("")
    add("| Finding | Count |")
    add("|---|---|")
    add(f"| Labels shared by more than one screen (same `message` and link type) | "
        f"{a['shared_label_groups']} labels, {a['shared_label_entries']} entries |")
    add(f"| Groups identical on every text field | {len(a['identical_text_groups'])} |")
    add(f"| Labels their own description does not support | {len(a['label_unsupported'])} |")
    add(f"| Toggle subjects with an on link but no off link | {len(a['on_without_off'])} |")
    add(f"| Toggle subjects with an off link but no on link | {len(a['off_without_on'])} |")
    add(f"| Entries with no link type (`originalType`) | {len(a['missing_type'])} |")
    add(f"| Entries with no validation deeplink | {len(a['missing_validation'])} |")
    add("")

    add("### 1.1 One label, many screens")
    add("")
    add("A step can only name what a customer reads on the screen. When one label covers "
        "many screens, the label cannot say which one; only the description can.")
    add("")
    add("| Label | Link type | Screens |")
    add("|---|---|---|")
    for g in a["largest_shared_labels"]:
        add(f"| {g['message']} | `{g['type']}` | {g['n']} |")
    add("")

    add("### 1.2 Entries no text can tell apart")
    add("")
    add("Different URIs, identical `message`, `description` and `qna_description`. No "
        "resolver can choose between these; either they are duplicates, or they need "
        "distinguishing text.")
    add("")
    for ids in a["identical_text_groups"]:
        add(f"- {', '.join(f'`{i}`' for i in ids)}")
    add("")

    add("### 1.3 Labels that name a different screen")
    add("")
    add("The label shares no subject word with the entry's own description or QnA text "
        "(after closing up hyphens, dropping plurals, joining two-word forms and matching "
        "6-letter stems). Gate [4] does not trust these to be the screen their label names, "
        "because a step that matches the label would be sent somewhere else.")
    add("")
    add("| Entry | Type | Label | Description |")
    add("|---|---|---|---|")
    for x in a["label_unsupported"]:
        add(f"| `{x['id']}` | `{x['type'] or '-'}` | {x['message']} | {x['description']} |")
    add("")

    add("### 1.4 One-sided toggles, missing types, missing validation")
    add("")
    if a["off_without_on"]:
        add(f"- Off link but no on link: {', '.join(a['off_without_on'])}. A step asking to "
            "turn it ON has no correct entry to resolve to.")
    if a["on_without_off"]:
        add(f"- On link but no off link: {', '.join(a['on_without_off'])}.")
    add(f"- No link type: {', '.join(f'`{i}`' for i in a['missing_type'])}. The polarity "
        "gate cannot place these as on, off or open.")
    add(f"- No validation deeplink: {', '.join(f'`{i}`' for i in a['missing_validation'])}.")
    add("")

    add("## 2. Settings steps in the supplied articles with no confident entry")
    add("")
    add("Every stepGroup across the 20 rows, by resolver outcome:")
    add("")
    add("| Decision | Reason | Count |")
    add("|---|---|---|")
    for d in u["decisions"]:
        add(f"| `{d['decision']}` | `{d['reason']}` | {d['n']} |")
    add("")
    add("`manual_category_forbids_deeplink` and `physical_interaction_not_a_settings_screen` "
        "are unlinked by the specification (guide §4.1), not gaps. The rest are below.")
    add("")
    if u["gaps"]:
        add("| Row | Article | Action | Outcome | Nearest candidates the gates refused |")
        add("|---|---|---|---|---|")
        for g in u["gaps"]:
            near = "; ".join(f"{n['message']} (`{n['id']}`, {n['verdict']})" for n in g["nearest"])
            add(f"| {g['row']} | {g['article']} | {g['action']} | "
                f"`{g['decision']}` / `{g['reason']}` | {near or '-'} |")
    else:
        add("None with this provider.")
    add("")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--provider", default="stub", help="stub | replay | gemini")
    ap.add_argument("--rate-limit-rpm", type=int, default=0)
    args = ap.parse_args()

    catalog_audit = audit(get_catalog().entries)
    steps = unresolved_steps(args.provider, args.rate_limit_rpm)
    generated = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    JSON_PATH.write_text(json.dumps({"generated_at_utc": generated, "catalog": catalog_audit,
                                     "unresolved": steps}, indent=2), encoding="utf-8")
    MD_PATH.write_text(render(catalog_audit, steps, generated), encoding="utf-8")
    print(f"wrote {MD_PATH.relative_to(ROOT)} and {JSON_PATH.relative_to(ROOT)}")
    print(f"  {len(catalog_audit['label_unsupported'])} unsupported labels, "
          f"{len(catalog_audit['identical_text_groups'])} identical groups, "
          f"{len(steps['gaps'])} unresolved Settings steps ({steps['provider']})")


if __name__ == "__main__":
    main()
